default:
    path: /
    controller: App\Controller\DefaultController::index


index:
    path: /
    controller: App\Controller\DefaultController::index

index_nouveaute:
    path: /nouveaute
    controller: App\Controller\DefaultController::index_nouveaute

index_biographie:
    path: /biographie
    controller: App\Controller\DefaultController::index_biographie

projets:
    path: /projets
    controller: App\Controller\DefaultController::projets

live:
    path: /live
    controller: App\Controller\DefaultController::live

blog:
    path: /blog
    controller: App\Controller\DefaultController::blog

hobbies:
    path: /hobbies
    controller: App\Controller\DefaultController::hobbies

getArticle:
    path: /get-article
    controller: App\Controller\ArticleController::getArticle

getArticleByType:
    path: /get-article-selection
    controller: App\Controller\ArticleController::getArticleBYType

countArticle:
    path: /count-article
    controller: App\Controller\ArticleController::countArticle

searchArticle:
    path: /search-article
    controller: App\Controller\ArticleController::searchArticle

agenda:
    path: /agenda
    controller: App\Controller\DefaultController::agenda


# lecture-article:
#     path: /lecture-article/{titre}
#     controller: App\Controller\ArticleController::lecture_article

new-article:
    path: /new-article
    controller: App\Controller\ArticleController::new_article

edit-article:
    path: /edit-article/{id}
    controller: App\Controller\ArticleController::edit_article

getProjet:
    path: /get-projet
    controller: App\Controller\ProjetController::getProjet

getProjetByType:
    path: /get-projet-selection
    controller: App\Controller\ProjetController::getProjetBYType

countProjet:
    path: /count-projet
    controller: App\Controller\ProjetController::countProjet

searchProjet:
    path: /search-projet
    controller: App\Controller\ProjetController::searchProjet

# lecture-projet:
#     path: /lecture-projet/{titre}
#     controller: App\Controller\ProjetController::lecture_projet

new-projet:
    path: /new-projet
    controller: App\Controller\ProjetController::new_projet

edit-projet:
    path: /edit-projet/{id}
    controller: App\Controller\ProjetController::edit_projet


CMS:
    path: /CMS
    controller: App\Controller\DefaultController::CMS




login:
    path: /login
    controller: App\Controller\UserController::login

account:
    path: /account
    controller: App\Controller\UserController::account

edit_info:
    path: /edit_info
    controller: App\Controller\UserController::edit_info

check_mail:
    path: /check_mail/{confirmationtoken}
    controller: App\Controller\UserController::checkmail

register:
    path: /register
    controller: App\Controller\UserController::register


reset_password_ask:
    path: /reset_password
    controller: App\Controller\UserController::reset_password_ask

change_password:
    path: /change_password
    controller: App\Controller\UserController::change_password

reset_password_check:
    path: /reset_password_check/{confirmationResetPasswordToken}
    controller: App\Controller\UserController::reset_password_check

logout:
    path: /logout
