default:
    path: /accueil
    controller: App\Controller\DefaultController::index


index:
    path: /presentation
    controller: App\Controller\DefaultController::index

index_nouveaute:
    path: /nouveaute
    controller: App\Controller\DefaultController::index_nouveaute

index_biographie:
    path: /biographie
    controller: App\Controller\DefaultController::index_biographie

projets:
    path: /projets
    controller: App\Controller\DefaultController::projets

live:
    path: /live
    controller: App\Controller\DefaultController::live

blog:
    path: /blog
    controller: App\Controller\DefaultController::blog

agenda:
    path: /agenda
    controller: App\Controller\DefaultController::agenda

contact:
    path: /contact
    controller: App\Controller\DefaultController::contact

lecture_article:
    path: /lecture_article
    controller: App\Controller\DefaultController::lecture_article



CMS:
    path: /CMS
    controller: App\Controller\DefaultController::CMS




login:
    path: /login
    controller: App\Controller\UserController::login

account:
    path: /account
    controller: App\Controller\UserController::account

edit_info:
    path: /edit_info
    controller: App\Controller\UserController::edit_info

check_mail:
    path: /check_mail/{confirmationtoken}
    controller: App\Controller\UserController::checkmail

register:
    path: /register
    controller: App\Controller\UserController::register


reset_password_ask:
    path: /reset_password
    controller: App\Controller\UserController::reset_password_ask

change_password:
    path: /change_password
    controller: App\Controller\UserController::change_password

reset_password_check:
    path: /reset_password_check/{confirmationResetPasswordToken}
    controller: App\Controller\UserController::reset_password_check

logout:
    path: /logout
