<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM3anGc7\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM3anGc7/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerM3anGc7.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerM3anGc7\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerM3anGc7\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'M3anGc7',
    'container.build_id' => 'cfab691d',
    'container.build_time' => 1543584282,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerM3anGc7');
