<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZTW3KNY\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZTW3KNY/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZTW3KNY.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZTW3KNY\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerZTW3KNY\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'ZTW3KNY',
    'container.build_id' => '28097054',
    'container.build_time' => 1543328497,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZTW3KNY');
